### ISSUE TITLE
Support for textarea

### ISSUE THREAD

**Issue by joeystdio** [KingMario/packages#2]
If you would change the directive selector to: 
`selector: '[upperCase]:not([lowerCase])'`

Then this directive would be usable for textarea as well.

**Comment by KingMario** [comment]
Thx @joeystdio 

I'm going to update it to
`selector: 'input[upperCase]:not([lowerCase]),textarea[upperCase]:not([lowerCase])',`

Do you think it's OK?

**Comment by joeystdio** [comment]
Yes, that will work as well. 👍

**Comment by KingMario** [comment]
@joeystdio
The fix is almost done. I'm making ngx-cleave-directive, ngx-lower-case-directive and ngx-upper-case-directive supporting textarea.

There's just one more thing. Do you think [ngx-trim-directive](https://www.npmjs.com/package/ngx-trim-directive) which is in the same repo should support textarea too?

Thx.

**Comment by joeystdio** [comment]
Thanks @KingMario !

Yes I think it's a good idea to add support for textarea in ngx-trim-directive as well.
