### ISSUE TITLE
Publish Ivy compatible `ngx-cleave-directive`

### ISSUE THREAD

**Issue by exequiel09** [KingMario/packages#26]
`ngx-cleave-directive@2.0.0` is not yet published on NPM.

See: https://github.com/KingMario/packages/issues/25#issuecomment-1094466870

Related to #25 

![Screen Shot 2022-04-25 at 8 21 23 AM](https://user-images.githubusercontent.com/1289472/165003000-9bdc498a-55a6-4a59-82e2-9ef8ed3f4897.png)

![Screen Shot 2022-04-25 at 8 22 14 AM](https://user-images.githubusercontent.com/1289472/165003031-0eab155d-a2ff-418d-b5b2-da389b28c267.png)

**Comment by KingMario** [comment]
@exequiel09 Thanks for the reminder.

ngx-cleave-directive v2.0.0 published.

The source is updated in the commit 59709bba78b647f42a7764bc5f93483786d8a036 of [ivy-compatibility branch](https://github.com/KingMario/packages/tree/ivy-compatibility).

But please note that, since it's an Angular upgrade over several main versions, the test and lint all failed.
