### ISSUE TITLE
Getting formatted value instead of raw value when binding the input to ngModel or FormControl

### ISSUE THREAD

**Issue by djawad98** [KingMario/packages#28]
Hi.
Thanks for your nice work.

But there's a problem with `Package 4. ngx-cleave-directive` when trying to bind the input value to a model or FormControl.
Instead of returning the rawValue it returns formattedValue with delimiters.
Expected value for ngModel or FormControl is something like `123456.789` and not `123,456.789`

I'm using options below:
```
    numeral: true,
    numeralDecimalScale: 3,
```

**Comment by KingMario** [comment]
Hi @djawad98,

Thanks for reporting this issue.

I'm afraid I can't achieve what you need because Angular runs `registerOnChange` before the cleave directive can do anything to hijack the internal `onChange` method to change the value for `viewToModelUpdate`, but there is a workaround, you can add an `onValueChanged` handler to your cleave options to get the rawValue.

Please refer to [onValueChanged](https://github.com/nosir/cleave.js/blob/master/doc/options.md#onvaluechanged) and this [example](https://stackblitz.com/edit/angular-ngx-cleave-directive-raw-value-got?file=src/main.ts) for details on how to implement it.

If your core requirement is to keep three decimal places, and if it is acceptable to set `numeralThousandsGroupStyle` to `none`, you may also consider setting it as such.

**Comment by KingMario** [comment]
Hi @djawad98 ,

I just noticed that the `viewToModelUpdate` has been exposed by NgControl. Let me see if it can help.

**Comment by KingMario** [comment]
Hi @djawad98 ,

Problem solved. Please install ngx-cleave-directive@2.1.0 to see if it works for you.

The updated code is in the ivy-compatibility branch. You can have a look at it. It's really simple using the `viewToModelUpdate` method exposed by the NgControl class.

If you run into any problem, feel free to leave a comment or raise an issue.

Thanks.
