### ISSUE TITLE
dirty flag issue

### ISSUE THREAD

**Issue by JakubFrankowski-zazoon** [KingMario/packages#30]
Hi I'm using cleave directive in my Form  but it makes it always "dirty".
I notice that this happens because of a line of code that is marked as 'hack for model -> view cleave'

```
 // hack for model -> view cleave
 setTimeout(() => this.dispatchEvent(el, 'input'), 0);
```

once event is dispatched angular thinks that user changed the value and marks FormControl as Dirty.

**Comment by KingMario** [comment]
Thanks for your issue report. @JakubFrankowski-zazoon 

Let me see how I can fix it.

**Comment by KingMario** [comment]
Hi @JakubFrankowski-zazoon, I noticed that the latest version of cleave directive doesn't hack for model -> view cleave. Could you please update the library to the latest version and check if this problem is gone.

The latest version code is in the ivy-compatibility branch.

https://github.com/KingMario/packages/blob/ivy-compatibility/projects/ngx-cleave-directive/src/lib/ngx-cleave.directive.ts

**Comment by KingMario** [comment]
Hi @JakubFrankowski-zazoon, I haven't heard from you for a long time; hence, I am closing this issue.

Please feel free to raise another issue if it's necessary.
